version: '3'
# CLONE-RCONF REMOVE START
volumes:
  etcd: {}
# CLONE-RCONF REMOVE END
services:
  premium-carousel-api:
    build:
      args:
        - APPNAME
        - MAIN_FILE=cmd/${APPNAME}/main.go
      context: .
      dockerfile: docker/dockerfile.dev
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    ports:
     - "${SERVICE_PORT}:8080"
    volumes:
      - ./:/app
    environment:
      CIRCUIT_BREAKER_FAILURE_RATIO: "0.5"
      CIRCUIT_BREAKER_CONSECUTIVE_FAILURE: "2"