apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-premium-carousel-api-configmap
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "premium-carousel-api.labels" . | indent 4 }}
data:
  # Your env variables should be written here.
  PROMETHEUS_ENABLED: "{{ .Values.core.prometheus.enabled }}"
  GOMS_HEALTH_PATH: "{{ .Values.core.healthcheck.path }}"
  ETCD_HOST: "{{ .Values.core.etcd.host }}"
  AD_HOST: "{{ .Values.core.ad.host }}"
  AD_PORT: "{{ .Values.core.ad.port }}"
  LOGGER_LOG_LEVEL: "{{ .Values.core.logger.logLevel }}"
  AD_IMAGE_SERVER_URL: "{{ .Values.core.ad.imageServerURL }}"
  CACHE_HOST: "{{ .Values.core.cache.host}}"
  DATABASE_NAME : "{{ .Values.core.database.name }}"
